### ISSUE TITLE
Open Privacy Tech logo design and branding

### ISSUE THREAD

**Issue by souravcipher** [openprivacytech/design#2]
Logo (standard formats like svg, png, jpg, and original ai files) also logo assets for social sites, website, etc. 

Brand guidelines should be nice and have design principles including fonts, color pallets, logo icons, lockup, etc. 

Open Source Design Post: https://opensourcedesign.net/jobs/jobs/2022-10-01-design-a-logo-and-branding-for-a-non-profit-working-on-open-source

If you're a designer and interested to contribute, 
please contact sourav@openprivacytech.org

**Comment by Simiann777** [comment]
Hello, I would like to design a logo and branding. Thank you
